### ISSUE TITLE
Given a set of angles/distances to landmarks, determine where robot is on field

### ISSUE THREAD

**Issue by cpdupuis** [KentridgeRobotics/2021Robot#12]
Using the information about visible landmarks, the robot needs to be able to determine where it is on the field. This will probably involve using the angles to each visible landmark, as well as its distance.

**Comment by yakiddinmeb** [comment]
Latest pull request should fulfill this, I hope.

**Comment by skallaher** [comment]
@yakiddinmeb , please close issues after the pull request is merged. 😃
