### ISSUE TITLE
Determine State of Gyroscope

### ISSUE THREAD

**Issue by skallaher** [KentridgeRobotics/2021Robot#3]
There seems to be some code indicating that there is a gyroscope on the robot.

This issue is to investigate the current state of that gyroscope as far as the code and hardware are concerned.

**Comment by nhl01** [comment]
The gyro returns -1 for most of the time, meaning that the data expires often. However, when it returns values, it is in degrees with clockwise being positive. When the robot turns in a full circle, the values roll back to 0. The -1 shows up the most when the robot is not in motion. Sometimes the values don't expire when the robot is stationary. Overall, the gyro is inconsistent.
