### ISSUE TITLE
Add new shooter hood command to adjust hood angle based on distance reported by LimeLight

### ISSUE THREAD

**Issue by cpdupuis** [KentridgeRobotics/2021Robot#5]
The LimeLight can tell us the distance to the target.

Add a new command to adjust the shooter hood. This command will read the distance from the LimeLight data in Network tables, and call the new method on ShooterHoodSubsystem to set the hood angle based on target distance.

**Comment by tonypunnacherry** [comment]
We also need to check if we're supposed to read Limelight information from the network tables or the current instance.
